#!/usr/bin/env python3

# Copyright (c) 2012 Riverbank Computing Limited.
#
# This file is part of metasip.
#
# This file may be used under the terms of the GNU General Public License v3
# as published by the Free Software Foundation which can be found in the file
# LICENSE-GPL3.txt included in this package.
#
# This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
# WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.


import sys
import os

from dip.io import IoManager, StorageError
from dip.io.storage.filesystem import FilesystemStorageFactory

from metasip import io_IoManager_read, Logger, Project, ProjectCodec


# Configure the i/o manager so we can use it for reading and writing projects
# to the filesystem.
IoManager.codecs.append(ProjectCodec())
IoManager.storage_factories.append(FilesystemStorageFactory())


def usage(rc = 2):
    """Print a usage/help message and quit the application.

    rc is the value to return as the exit code to the calling process.
    """
    if rc == 0:
        f = sys.stdout
    else:
        f = sys.stderr

    f.write("Usage:\n")
    f.write("    msip [-h] [-g dir] [-O] [gui-args] [--] [project]\n")
    f.write("where:\n")
    f.write("    -h         display this help message\n")
    f.write("    -g dir     generate the .sip files in dir\n")
    f.write("    -O         generate .sip files for old versions of SIP\n")
    f.write("    gui-args   arguments passed to the GUI\n")
    f.write("    --         stop GUI argument parsing\n")
    f.write("    project    the project file\n")

    sys.exit(rc)


def load_batch_project(prjname):
    """ Load an existing project in anticipation of doing some batch
    processing.

    :param prjname:
        is the location of the project.
    :return:
        the project.
    """

    if not prjname:
        fatal("Specify the name of an existing project file")

    try:
        prj = io_IoManager_read(Project(), 'metasip.formats.project', prjname)
    except StorageError as e:
        fatal(e.error)

    return prj


def generate(prjname, gendir, latest_sip):
    """
    Generate the .sip files for a project and return an exit code or 0 if there
    was no error.

    prjname is the name of the project file.
    gendir is the directory in which to generate the .sip files.
    """
    if not os.path.isdir(gendir):
        fatal("%s is not an existing directory" % gendir)

    prj = load_batch_project(prjname)

    # Generate each module.
    for mod in prj.modules:
        if not prj.generateModule(Logger, mod, gendir, False, latest_sip=latest_sip):
            fatal(prj.diagnostic)

    # No error if we have got this far.
    return 0


def launchGUI(prjname, guiargs):
    """ Launch the GUI for a project.

    :param prjname:
        is the name of the project file.  It is None if there is none.
    :param guiargs:
        is a list of any GUI specific command line arguments.
    :return:
        the exit code or 0 if there was no error.
    """

    from PyQt4.QtCore import QSettings
    from PyQt4.QtGui import QApplication

    from dip.shell import IShell
    from dip.shell.shells.main_window import MainWindowShell
    from dip.shell.tools.dirty import DirtyTool
    from dip.shell.tools.model_manager import ModelManagerTool
    from dip.shell.tools.quit import QuitTool

    from metasip import ProjectEditorTool, ProjectFactory

    app = QApplication(guiargs)

    # Define the shell.
    editor_tool = ProjectEditorTool(model_policy='one')

    shell = MainWindowShell(main_area_policy='single',
            tool_factories=[DirtyTool,
                    lambda: ModelManagerTool(
                            model_factories=[ProjectFactory()]),
                    lambda: editor_tool,
                    QuitTool],
            window_title_template="[view][*]")

    # Create the shell.
    ui = shell()

    # Handle any project passed on the command line.
    if prjname is not None:
        # FIXME: Add a progress dialog as this may take some time and the GUI
        #        is not yet visible.
        IShell(ui).open(prjname, 'metasip.formats.project',
                'metasip.tools.project_editor')

    # Get the user settings and adjust the layout.
    settings = QSettings('riverbankcomputing.com', 'MetaSIP')

    settings.beginGroup('GUI')

    ui.restoreState(settings.value('mainState'))
    ui.restoreGeometry(settings.value('mainGeometry'))

    # If there was no project then the editor will not have been created yet.
    if editor_tool.project is not None:
        editor_tool.splitter.restoreState(settings.value('mainSplitter'))

        settings.beginGroup('mainPane0')
        editor_tool.editor.loadGUILayout(settings)
        settings.endGroup()

    settings.endGroup()

    # Display the GUI.
    ui.show()

    rc = app.exec()

    # Save the GUI layout.
    settings.beginGroup('GUI')

    settings.setValue('mainState', ui.saveState())
    settings.setValue('mainGeometry', ui.saveGeometry())
    settings.setValue('mainSplitter', editor_tool.splitter.saveState())

    settings.beginGroup('mainPane0')
    editor_tool.editor.saveGUILayout(settings)
    settings.endGroup()

    settings.endGroup()

    return rc


def fatal(msg):
    """
    Display an error message and exit with a return code of 1.

    msg is the text of the message, excluding newlines.
    """
    sys.stderr.write("msip: %s\n" % msg)
    sys.exit(1)


if __name__ == "__main__":
    # Parse the arguments.
    argv = sys.argv[1:]

    gendir = None
    latest_sip = True
    guiargs = []

    nxt = 0
    skip = False

    for arg in argv:
        nxt += 1

        if skip:
            skip = False
            continue

        if arg == "-h":
            usage(0)

        if arg == "-O":
            latest_sip = False
        elif arg == "-g":
            if nxt >= len(argv):
                usage()

            gendir = argv[nxt]
            skip = True
        elif arg == "--":
            # Stop parsing GUI arguments.
            break
        elif arg.startswith("-") or guiargs:
            guiargs.append(arg)
        else:
            nxt -= 1
            break

    # There might be one argument left which is the project name.
    unused = len(argv) - nxt

    if unused > 1:
        usage()

    if unused == 1:
        prjname = argv[-1]
    else:
        prjname = None

    # Carry out the required action.
    if gendir:
        rc = generate(prjname, gendir, latest_sip)
    else:
        rc = launchGUI(prjname, guiargs)

    sys.exit(rc)
